In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.python.keras import backend as K
import tensorflow as tf
import collections
import numpy as np
from openpyxl import load_workbook
from openpyxl import Workbook
from pandas import ExcelWriter
from funciones import ErrorAuno,ErrorAcero,TensorUpdatePosicionInicial,TensorUpdateCiclo

from tensorflow.keras.layers import (Activation, AveragePooling2D, BatchNormalization, Cropping2D,
                                     Concatenate, Conv1D, Conv2D, Dense, DepthwiseConv2D, Dropout,
                                     Embedding, Flatten, GlobalAveragePooling2D, Lambda, MaxPool2D,
                                     MaxPooling1D, ReLU, Reshape, ZeroPadding2D)

In [2]:

tensor_original=tf.convert_to_tensor([38, 38, 32769])
static_Error0_1= ([49087,16384],[49087,64],[65471,514]) 
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor_original,faults[:,0])
print('tensor_original',tensor_original)
tensor_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print(tensor_with_error)

tensor_original tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)
tf.Tensor([16422   102 33283], shape=(3,), dtype=int32)


In [3]:
import tensorflow as tf
import numpy as np
tensor_original=tf.convert_to_tensor([40167,61311,64511,22,17,37,30,38 ])
print('tensor_original',tensor_original)
static_Error0_1= ([7927,528],[28671,0],[57343,1024],[65535,12],[65518,4],[65535,32768],[49087,0] ,[49087,0])
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor_original,faults[:,0])
print('faults[:,0]',faults[:,0])
tensor_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print(tensor_with_error)



tensor_original tf.Tensor([40167 61311 64511    22    17    37    30    38], shape=(8,), dtype=int32)
faults[:,0] tf.Tensor([ 7927 28671 57343 65535 65518 65535 49087 49087], shape=(8,), dtype=int32)
tf.Tensor([ 7927 28543 57343    30     4 32805    30    38], shape=(8,), dtype=int32)


In [4]:
import tensorflow as tf
a=tf.math.not_equal(vb_and_mask,vm_and_mask)
print('a',a)
error_a_1=tf.math.greater(v_m,v_b ) # El error es a 1 y aplico la variante con_error_a_1
print('error_a_1',error_a_1)
index_values_error_a_1=tf.where(tf.logical_and(a,error_a_1)==True)
index_values_error_a_1 = tf.cast(index_values_error_a_1, dtype=tf.int32)
print('index_values_error_a_1',index_values_error_a_1)
val=tf.gather_nd(tf.where(valores_afectados),index_values_error_a_1)## tomo los indices del tensor original qu ese cambiaran
val = tf.cast(val, dtype=tf.int32)
print('val ',val)
#

#### agraegado para si se encuentra error a 0 en la posición más significativa  esto 
error_a_0=tf.math.greater(v_b,v_m)
index_values_error_a_0=tf.where(tf.logical_and(a,error_a_0)==True)
index_values_error_a_0 = tf.cast(index_values_error_a_0, dtype=tf.int32)
print('index_values_error_a_0',index_values_error_a_0)
#index_0=index_values_error_a_0.numpy()
val_0=tf.gather_nd(tf.where(valores_afectados),index_values_error_a_0)## tomo los indices del tensor original que se cambiaran
val_0 = tf.cast(val_0, dtype=tf.int32)
print('val_0',val_0)

if tf.size(val)> 0: 
        tensor_act = tf.tensor_scatter_nd_update(tensor_act, val, tf.convert_to_tensor([0]*np.size(val) ))
        valores_afectados=tf.tensor_scatter_nd_update(valores_afectados,val,tf.convert_to_tensor([False]*np.size(val)))
    
if tf.size(val_0)>0:
        tensor_act = tf.tensor_scatter_nd_update(tensor_act, val_0, tf.convert_to_tensor([0]*np.size(val_0) ))
        valores_afectados=tf.tensor_scatter_nd_update(valores_afectados,val_0,tf.convert_to_tensor([False]*np.size(val_0)))
        print('tensor_act',tensor_act)
    
print('tensor_act',tensor_act)
print(valores_afectados)

mask

a tf.Tensor([False False False], shape=(3,), dtype=bool)
error_a_1 tf.Tensor([ True  True  True], shape=(3,), dtype=bool)
index_values_error_a_1 tf.Tensor([], shape=(0, 1), dtype=int32)
val  tf.Tensor([], shape=(0, 1), dtype=int32)
index_values_error_a_0 tf.Tensor([], shape=(0, 1), dtype=int32)
val_0 tf.Tensor([], shape=(0, 1), dtype=int32)
tensor_act tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)
tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


<tf.Tensor: shape=(), dtype=int32, numpy=32768>

In [5]:

mask=tf.convert_to_tensor(32768,dtype=tf.int32)



#crea un tensor de (T and F),donde en T están los valores afectados por los errores inyectados
# esta matriz es la que controla si ya no hay cambios pendientes porque todos los valores han sido analizados y
#detiene el ciclo para no iterar innecesariamente

valores_afectados=tf.math.not_equal(tensor_original,tensor_with_error)
print('valores_afectados',valores_afectados)  

# Se extraen los valores que fueron afectados por los errores
v_m=tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True))
print('valores afectados por los errores' ,v_m)

#valores que se deberian escribir
v_b=tf.gather_nd(tensor_original,tf.where(valores_afectados==True))
print('valores que se deberian escribir' ,v_b)
#a=np.size(v_m)
# Creo una máscara de 0 del con la cantidad de errores afectados para ir llevando el contrl de los cambios 
#mask_0=tf.convert_to_tensor([0]*a)
mask_0=tf.constant(0)
print('mask_0',mask_0)

vb_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_original,tf.where(valores_afectados==True)),mask)
print('vb_and_mask',vb_and_mask)
vm_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True)),mask)


tensor_act=tensor_original 

valores_afectados tf.Tensor([ True  True  True  True  True  True False False], shape=(8,), dtype=bool)
valores afectados por los errores tf.Tensor([ 7927 28543 57343    30     4 32805], shape=(6,), dtype=int32)
valores que se deberian escribir tf.Tensor([40167 61311 64511    22    17    37], shape=(6,), dtype=int32)
mask_0 tf.Tensor(0, shape=(), dtype=int32)
vb_and_mask tf.Tensor([32768 32768 32768     0     0     0], shape=(6,), dtype=int32)


## cosas nuevas del Mors par ahacer el shift

In [17]:
#tensor_original tf.Tensor([40167 61311 64511    22    17    37    30    38], shape=(8,), dtype=int32)
#tf.Tensor                ([ 7927 28543 57343    30     4 32805    30    38], shape=(8,), dtype=int32)

In [18]:
tensor = tf.bitwise.left_shift(v_m, 1)
tensor

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 15854,  57086, 114686,     60,      8,  65610])>

In [19]:

static_Error0_1= ([7927,528],[28671,0],[57343,1024],[65535,12],[65518,4],[65535,32768])
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor,faults[:,0])
print('faults[:,0]',faults[:,0])
tensor_new_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print(tensor_new_with_error)


faults[:,0] tf.Tensor([ 7927 28671 57343 65535 65518 65535], shape=(6,), dtype=int32)
tf.Tensor([ 7926 20222 40958    60    12 32842], shape=(6,), dtype=int32)


In [20]:
tensor = tf.bitwise.right_shift(tensor_new_with_error, 1)
tensor

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3963, 10111, 20479,    30,     6, 16421])>

In [22]:
tensor = tf.bitwise.left_shift(tensor_original, 1)
tensor

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 80334, 122622, 129022,     44,     34,     74,     60,     76])>

In [23]:
static_Error0_1= ([7927,528],[28671,0],[57343,1024],[65535,12],[65518,4],[65535,32768],[49087,0] ,[49087,0])
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor,faults[:,0])
print('faults[:,0]',faults[:,0])
tensor_new_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print(tensor_new_with_error)


faults[:,0] tf.Tensor([ 7927 28671 57343 65535 65518 65535 49087 49087], shape=(8,), dtype=int32)
tf.Tensor([ 6870 20222 55294    44    38 32842    60    12], shape=(8,), dtype=int32)


In [24]:
tensor = tf.bitwise.right_shift(tensor_new_with_error, 1)
tensor

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3435, 10111, 27647,    22,    19, 16421,    30,     6])>

In [ ]:
                                              7927  28543   57343    30      4    32805     30    38            
    tensor_original tf.Tensor([              40167  61311   64511    22      17    37       30    38]
                 

In [21]:
mask=tf.bitwise.right_shift(mask,1)
print(mask)
v_m=tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True))
print('vm' ,v_m)

#valores que se deberian escribir
v_b=tf.gather_nd(tensor_original,tf.where(valores_afectados==True))
print('vb', v_b)


tf.Tensor(16384, shape=(), dtype=int32)
vm tf.Tensor([ 7927 28543 57343    30     4 32805], shape=(6,), dtype=int32)
vb tf.Tensor([40167 61311 64511    22    17    37], shape=(6,), dtype=int32)


In [6]:
mask = tf.convert_to_tensor([mask] * tf.size(v_b))
print(mask)

tf.Tensor([16384 16384 16384], shape=(3,), dtype=int32)


In [6]:
for i in range(15):
# esto es equivalente a un: if VB&&mask == VM&&mask then mask = mask >> 1 else mask = mask, para cada elemento del tensor mask
    mask = tf.where(tf.equal(tf.bitwise.bitwise_and(v_b,mask), tf.bitwise.bitwise_and(v_m,mask)),
                    tf.bitwise.right_shift(mask, 1),mask)
print('mask',mask)

mask tf.Tensor([8192    8   16], shape=(3,), dtype=int32)


In [7]:
new_values = tf.where(tf.math.greater(tf.bitwise.bitwise_and(v_b,0b01111111_11111111),tf.bitwise.bitwise_and(v_m,0b01111111_11111111)),
                      tf.bitwise.bitwise_or(v_b,tf.maximum(mask-1,0)), tf.bitwise.bitwise_and(v_b,tf.bitwise.invert(tf.maximum(mask-1,0))))
print(new_values)


tf.Tensor([65535    16    31], shape=(3,), dtype=int32)


In [8]:
tensor_act = tf.tensor_scatter_nd_update(tensor_act, tf.where(valores_afectados==True), new_values )

In [9]:
tensor_act

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([    0,     0, 65535,    16,    31,     0,    30,    38])>

In [ ]:
 0     0 65535    16    31     0    30    38