In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.python.keras import backend as K
import tensorflow as tf
import collections
import numpy as np
from openpyxl import load_workbook
from openpyxl import Workbook
from pandas import ExcelWriter
from funciones import ErrorAuno,ErrorAcero,TensorUpdatePosicionInicial,TensorUpdateCiclo

from tensorflow.keras.layers import (Activation, AveragePooling2D, BatchNormalization, Cropping2D,
                                     Concatenate, Conv1D, Conv2D, Dense, DepthwiseConv2D, Dropout,
                                     Embedding, Flatten, GlobalAveragePooling2D, Lambda, MaxPool2D,
                                     MaxPooling1D, ReLU, Reshape, ZeroPadding2D)

In [7]:
##### Funciones para trabajar cada caso según el tipo de error si el mismo está dado por la escritura de un 0 cuando
##### debía ser un 1(ErrorAcero) o viceversa. Se ha desarrollado un algoritmo que permite colocar luego del primer bit con
####error encontrado en el resto de las posiciones a 0 o a unos : Se analizan los valores comenzando por el BMS(Bit más
#signif)comparando el valor con el error y el valor que se debe escribir correcto donde haya un cambio de valor se analiza
#### si el cambio es de un 0 x 1 se coloca el resto de los bits a 0, y luego se inyectan los demás errores y si el cambio
#### es de un 1 x 0 se colocan los bits siguientes a 1 y se mantienen los errores restantes haciendo un Bitwise con los
#valores  generados por errores estaticos a 1 o a 0

In [9]:
# Conversión del tensor generado por la red a naturales: para ello se multiplica el número generado por la red que es un 
#un número real x 2**bit de la parte fraccionaria colocando el valor en un entero de 32 bits(de esta forma se convierten a 
# enteros) luego para llevarlo a naturales(a los valores negativos se les suma 2**al tamaño de la palabra que en este caso
# es de 16 bits)

In [ ]:
test
VB:38 38 32769
Vm: 16422   102 33283 
error _0 49087 ,49087,49087
error_1 16384, 64,514


0000000000100110 38 vb
0100000000100110 16422 vm
0100000000000000 mask 16384 error 1 vm>vb
0011111111111111 mask-1 16383
1100000000000000 n_mask 49152
0000000000100110 vb
0000000000000000 btwand
1011111110111111 and error_0 49087
0000000000000000
0100000000000000 or 16384
010000000000000016384

numero 2
0000000000100110 38
0000000001100110 102
00000000010000000 mask 128
00000000001111111mas-1 127
11111111110000000 n_mask
0000000000100110
0000000000000000 and n_mask
1011111110111111
0000000000000000
0000000001000000
0000000001000000 64
numeo 3
1000000000000001 32769
1000001000000011 33283
0000001000000000 512
0000000111111111 masl-1 511
1111111000000000n_mask
1000000000000001
1000000000000000 32768
1011111110111111
1000000000000000b32768
0000001000000010
1000001000000010 33282

test
0000000000010110 22 vb
0000000000011110 30 v_m
0000000000001000 8 mask
0000000000000111 mak-1
1111111111111000 n_mak
0000000000010110 vb
0000000000010000 16











    

In [17]:
int('0b10000000_00000000',2)

32768

In [19]:
bin( 33283 )

'0b1000001000000011'

In [ ]:
0b1000000000000001
0b1000001000000011

## Test 1

In [9]:
import tensorflow as tf
tensor_original=tf.convert_to_tensor([38, 38, 32769])
static_Error0_1= ([49087,16384],[49087,64],[65471,514]) 
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor_original,faults[:,0])
print('tensor_original',tensor_original)
tensor_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print(tensor_with_error)

tensor_original tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)
tf.Tensor([16422   102 33283], shape=(3,), dtype=int32)


In [7]:
mask=32768
mask = tf.where(tf.equal(tf.bitwise.bitwise_and(tensor_original,mask), tf.bitwise.bitwise_and(tensor_with_error,mask)),
                    tf.bitwise.right_shift(mask, 1),mask)
mask

## Test 2

In [2]:
import tensorflow as tf
import numpy as np
tensor_original=tf.convert_to_tensor([40167,61311,64511,22,17,37,30,38 ])
print('tensor_original',tensor_original)
static_Error0_1= ([7927,528],[28671,0],[57343,1024],[65535,12],[65518,4],[65535,32768],[49087,0] ,[49087,0])
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor_original,faults[:,0])
print('faults[:,0]',faults[:,0])
tensor_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print('tensor_with_error',tensor_with_error)



tensor_original tf.Tensor([40167 61311 64511    22    17    37    30    38], shape=(8,), dtype=int32)
faults[:,0] tf.Tensor([ 7927 28671 57343 65535 65518 65535 49087 49087], shape=(8,), dtype=int32)
tensor_with_error tf.Tensor([ 7927 28543 57343    30     4 32805    30    38], shape=(8,), dtype=int32)


In [13]:
mask=32768
mask = tf.where(tf.equal(tf.bitwise.bitwise_and(tensor_original,mask), tf.bitwise.bitwise_and(tensor_with_error,mask)),
                    tf.bitwise.right_shift(mask, 1),mask)
mask

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([32768, 32768, 16384, 16384, 16384, 32768, 16384, 16384])>

In [20]:
tf.equal(mask, 32768)

<tf.Tensor: shape=(8,), dtype=bool, numpy=array([ True,  True, False, False, False,  True, False, False])>

In [18]:
#tf.where(tf.equal(mask, 32768)==True)
b=tf.cast(tf.where(tf.equal(mask, 32768)==True), dtype=tf.int32)

In [21]:
tensor_act = tf.tensor_scatter_nd_update(tensor_original, tf.where(mask==32768), tf.convert_to_tensor([0] * tf.experimental.numpy.size(b)))

In [22]:
tensor_act

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([    0,     0, 64511,    22,    17,     0,    30,    38])>

In [ ]:
t_orig= 40167 61311 64511    22    17    37    30    38
t_error= 7927 28543 57343    30     4 32805    30    38

In [ ]:
 while= 0     0     65535    16    31     0    30    38
 for=   0,    0,    64511,   22,   17,    0,    30,    38])>   

In [40]:
new_values = tf.where(tf.math.greater(tf.bitwise.bitwise_and(tensor_original,16384),tf.bitwise.bitwise_and(tensor_with_error,16384)),
                      tf.bitwise.bitwise_or(tensor_original,tf.maximum(mask-1,0)), tf.bitwise.bitwise_and(tensor_original,tf.bitwise.invert(tf.maximum(mask-1,0))))

In [41]:
new_values

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([    0,     0, 49152,     0,     0,     0,     0,     0])>

In [ ]:
vb 40167,61311,64511
error_0: 7927,28671,57343
error_1: 528,0,1024
0.Antes de entrar al ciclo
1001110011100111 vb 40167
0001111011110111 vm 7927
0001111011110111 error_0 7927
0001111011110111 and
0000001000010000 error_1 528
0001111011110111 7927
Prueba
mask=32768     
n_mask=mask-1   0111111111111111
000000000000000

1. Antes de entrar al ciclo
1110111101111111 vb 61311
0110111101111111 vm 28543 
0110111111111111 error_0 28671
0110111101111111 28543
0000000000000000 error_1 
0110111101111111 28543
Prueba
mask=32768     
n_mask=(mask-1) 0111111111111111
1110111101111111 vb
0111111111111111 n_mask
1111111111111111 or 65535
0110111111111111 and error_0 28671
0110111111111111
0000000000000000 error_1
0110111111111111 or  28671 

3. iteración i=1
1111101111111111 vb 64511
1101111111111111 v_m 57343
1101111111111111 error_0 57343
1101101111111111
0000010000000000 error_1 1024
1101111111111111 57343

Prueba
mask=8192 0010000000000000    
n_mask=(mask-1)0001111111111111
1111101111111111 vb 64511
0001111111111111  n_mask
1111111111111111 or n_mask
1101111111111111 error_0 57343
1101111111111111 and
0000010000000000 error_1 1024
1101111111111111  57343


 528     0 50176

1111101111111111v_b
1000000000000000
1000000000000000 vb_mask
1101111111111111- v_m
1000000000000000
1000000000000000 vm_mask
vb_mask!=vm_mask  false
v_m>v_b false



In [170]:
bin(28543 )

'0b110111101111111'

# Test 3

In [ ]:
 VB= 0b01101100_00000000,0b10101010_11100000,0b00000000_00011000
VM= 0b11101100_00000000,0b00101110_11100000,0b00000000_00000000

0110110000000000 27648
1110110000000000 60416
1000000000000000 32768 mask Error a 1 xq VM>VB
0111111111111111 mask-1
1000000000000000 n_mask

algoritmo
VBandN_mask
0110110000000000
1000000000000000
0000000000000000


numero 2
1010101011100000 43744
0010111011100000 12000
1000000000000000




In [11]:
int('0010111011100000',2)

12000

##Prueba para entrar a errores por 0

In [10]:
valores_afectados=tf.math.not_equal(tensor_original,tensor_with_error)
print('valores_afectados',valores_afectados)  

# Se extraen los valores que fueron afectados por los errores
v_m=tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True))
print('valores afectados por los errores' ,v_m)

#valores que se deberian escribir
v_b=tf.gather_nd(tensor_original,tf.where(valores_afectados==True))
print('valores que se deberian escribir' ,v_b)
#a=np.size(v_m)
# Creo una máscara de 0 del con la cantidad de errores afectados para ir llevando el contrl de los cambios 
#mask_0=tf.convert_to_tensor([0]*a)

valores_afectados tf.Tensor([ True  True  True], shape=(3,), dtype=bool)
valores afectados por los errores tf.Tensor([16422   102 33283], shape=(3,), dtype=int32)
valores que se deberian escribir tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)


In [40]:
mask = tf.where(tf.equal(tf.bitwise.bitwise_and(v_b,32768), tf.bitwise.bitwise_and(v_m,32768)),
                    tf.bitwise.right_shift(32768, 1),32768)
print('mask',mask)
values_0=tf.where(mask==32768)
print('values_0',values_0)

mask tf.Tensor([32768 32768 16384 16384 16384 32768], shape=(6,), dtype=int32)
values_0 tf.Tensor(
[[0]
 [1]
 [5]], shape=(3, 1), dtype=int64)


In [42]:
val = tf.gather_nd(tf.where(valores_afectados), tf.where(mask==32768))
val

<tf.Tensor: shape=(3, 1), dtype=int64, numpy=
array([[0],
       [1],
       [5]], dtype=int64)>

In [33]:
new_values = tf.where(tf.math.greater(tf.bitwise.bitwise_and(v_b,16384),tf.bitwise.bitwise_and(v_m,16384)),
                      tf.bitwise.bitwise_or(v_b,tf.maximum(mask-1,0)), tf.bitwise.bitwise_and(v_b,tf.bitwise.invert(tf.maximum(mask-1,0))))
new_values

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([32768, 32768, 49152,     0,     0,     0])>

In [14]:
new_values = tf.where(tf.math.greater(tf.bitwise.bitwise_and(v_b,32768),tf.bitwise.bitwise_and(v_m,32768)),
                      tf.bitwise.bitwise_or(v_b,tf.maximum(mask-1,0)), tf.bitwise.bitwise_and(v_b,tf.bitwise.invert(tf.maximum(mask-1,0))))
new_values

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([65535, 65535, 49152,     0,     0,     0])>

In [89]:
static_Error0_1= ([7927,528],[28671,0],[57343,1024],[65535,12],[65518,4],[65535,32768],[49087,0] ,[49087,0])
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor_act,faults[:,0])
print('faults[:,0]',faults[:,0])
tensor_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print(tensor_with_error)



faults[:,0] tf.Tensor([ 7927 28671 57343 65535 65518 65535 49087 49087], shape=(8,), dtype=int32)
tf.Tensor([ 7696 28543 57343    28    14 32805    30    38], shape=(8,), dtype=int32)


## Declaración de variables y preparación de los datos que entran al ciclo

In [ ]:
values_to_run
mask
v_m
v_b
mask_0
valores_afectados
matriz_control_cambios
valores_afec_static_0_Error
valores_afec_static_1_Error
vb_and_mask
vm_and_mask
tensor_act
values_to_run

In [ ]:
Todo esto ha de ser una función que será llamada de la funcion apply round luego de inyectar los errores , pasando el tensor 
original que llega con problemas , el tensor con los errores y la máscara . Con el fin de obtener el tensor actualizado con los valores
redondeados .

In [11]:
#Se crea un tensor variable donde se guardarán los valores en cada ciclo que aún no se han encontrado la posición con error
#y hay que continuar analizando con mask>>1
# se cra un tensor con el valos de la máscara inicial la cual es 1000000000000000
values_to_run=tf.Variable(0)
mask=tf.convert_to_tensor(32768)

#crea un tensor de (T and F),donde en T están los valores afectados por los errores inyectados
# esta matriz es la que controla si ya no hay cambios pendientes porque todos los valores han sido analizados y
#detiene el ciclo para no iterar innecesariamente

valores_afectados=tf.math.not_equal(tensor_original,tensor_with_error)
print('valores_afectados',valores_afectados)  

# Se extraen los valores que fueron afectados por los errores
v_m=tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True))
print('valores afectados por los errores' ,v_m)

#valores que se deberian escribir
v_b=tf.gather_nd(tensor_original,tf.where(valores_afectados==True))
print('valores que se deberian escribir' ,v_b)
#a=np.size(v_m)
# Creo una máscara de 0 del con la cantidad de errores afectados para ir llevando el contrl de los cambios 
#mask_0=tf.convert_to_tensor([0]*a)
mask_0=tf.constant(0)
print('mask_0',mask_0)

# inicializo los valores de comienzo y fin del ciclo teniendo en cuenta que pueden haber errores hasta la posición 15 de
# una palabra
i=tf.constant(0)
out=tf.constant(16)
print(' out inicial',(out))
print('i inicial', i)


#matriz_control(esta la cree pero al final no la uso luego que verifique todo puede ser eliminada sino hace falta)
#matriz_control=tf.equal(tensor_original,tensor_with_error)
matriz_control_cambios=tf.equal(v_b,v_m)
print('matriz_control_cambios',matriz_control_cambios)

# Tensores con los valores de errores en 0 y 1 que propiciaron cambios en el tensor original
valores_afec_static_0_Error=tf.gather_nd(faults[:,0], tf.where(tf.math.not_equal(tensor_original,tensor_with_error)))
valores_afec_static_1_Error=tf.gather_nd(faults[:,1], tf.where(tf.math.not_equal(tensor_original,tensor_with_error)))
print('valores_afec_static_0_Error',valores_afec_static_0_Error)
print('valores_afec_static_1_Error',valores_afec_static_1_Error)

vb_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_original,tf.where(valores_afectados==True)),mask)
print('vb_and_mask',vb_and_mask)
vm_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True)),mask)
vm_and_mask
##### 'aquí actualizo el tensor con los nuevos valores de igual a mask'
print('vm_and_mask',vm_and_mask)
#tf.gather_nd(v_b,tf.where(tf.equal(vb_and_mask,vb_and_mask)):
#a=np.size(v_m)

## la primera vez tensor_actu= tensor original creo esta variable para ir actualizando el tensor con los nuevos valores 
#generados con la técnica del redeondeo

tensor_act=tensor_original 

valores_afectados tf.Tensor([ True  True  True], shape=(3,), dtype=bool)
valores afectados por los errores tf.Tensor([16422   102 33283], shape=(3,), dtype=int32)
valores que se deberian escribir tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)
mask_0 tf.Tensor(0, shape=(), dtype=int32)
 out inicial tf.Tensor(16, shape=(), dtype=int32)
i inicial tf.Tensor(0, shape=(), dtype=int32)
matriz_control_cambios tf.Tensor([False False False], shape=(3,), dtype=bool)
valores_afec_static_0_Error tf.Tensor([49087 49087 65471], shape=(3,), dtype=int32)
valores_afec_static_1_Error tf.Tensor([16384    64   514], shape=(3,), dtype=int32)
vb_and_mask tf.Tensor([    0     0 32768], shape=(3,), dtype=int32)
vm_and_mask tf.Tensor([    0     0 32768], shape=(3,), dtype=int32)


In [14]:
## depurar para colocar en o donde hay problema en el primer bit y luego que entre al ciclo esto va a ser una función 
#a:Matriz de True and False donde True son las posiciíones donde vb_and_mask y vm_and_mask son diferentes
#por tanto existe un error en la posición más significativa 
#b:Matriz de True and False donde True  es la posiciíon dende se cumple que (v_m>v_b ) 
#c: Indice donde la matriz a y b son verdaderas por tanto el error esta dado por un 1 
#values_to_change:los valores de v_b en las posiciones c que han se ser enviados a la función ErroraUno para su transformación
#val_afec_0_Error_to_change:Valores que corresponden los el error a 0 
#val_afec_1_Error_to_change:valores que corresponden con elerror a 1  Creo que ya no son necesarias 
#index: devuelve el valor de c en una variable numpy
#val:devuelve una lista de elementos que corresponden a los indices de valores afectados ==True que serán los indices a transformar
#error_a_0: Matriz de True and False donde True  es la posiciíon dende se cumple que (v_b>v_m )
#index_values_error_a_0:Indice donde la matriz a y error_a_0 que son verdaderas por tanto el error esta dado por un 0 
#val_0=devuelve una lista de elementos que corresponden a los indices de valores afectados ==True que serán los indices a transformar
#tensor_act: devuelve el tensor ya transormado con los elementos en las posiciones correspondientes donde se han encontrado los casos analizados


In [12]:
def ErrorPosicionInicial(v_m,v_b):
    b=tf.math.greater(v_m,v_b ) # El error es a 1 y aplico la variante con_error_a_1
    print('b Vm>Vb',b)
    c=tf.where(tf.logical_and(a,b)==True)
    print('c',c)
    print('tamaño de c',tf.size(c))
    print(' c Indices de los valores a transformar a 0',c)
    values_to_change=tf.gather_nd(v_b,c)
    print('mask_0 desdes update', mask_0)
    index=c.numpy()
    print('cnumpy',index)
    print('valores_afectados',valores_afectados)
    val=tf.gather_nd(tf.where(valores_afectados),index)## tomo los indices del tensor original qu ese cambiaran
    print('val',val)
    #mask_0=tf.add(mask_0,tf.size(val))
    return(val)

In [13]:
def TensorUpdatePosicionInicial(tensor_act,val,valores_afectados,mask_0,tensor_with_error,faults): 
    print('Dentro de TensorUpdatePosicionInicial')
    tensor_act = tf.tensor_scatter_nd_update(tensor_act, val, tf.convert_to_tensor([0]*np.size(val) ))
    valores_afectados=tf.tensor_scatter_nd_update(valores_afectados,val,tf.convert_to_tensor([False]*np.size(val)))
    print('valores_afectados dentro de error 0 en primera posición',valores_afectados )
    mask_0=tf.add(mask_0,tf.size(val))
    print('tensor_act funciion a 0',tensor_act)
    print('mask_0',mask_0)
    print('valores_afectados',valores_afectados)
    print('tensor_with_error',tensor_with_error)
    #tensor_with_error_run= tf.gather_nd(tensor_with_error,tf.where(valores_afectados ==True))   
    v_b=tf.gather_nd(tensor_act,tf.where(valores_afectados==True))
    print('v_b',v_b)
    v_m=tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True) )
    print('v_m',v_m)
    valores_afec_static_0_Error=tf.gather_nd(faults[:,0],tf.where(valores_afectados==True))
    print('valores_afec_static_0_Error', valores_afec_static_0_Error)
    valores_afec_static_1_Error=tf.gather_nd(faults[:,1],tf.where(valores_afectados==True))
    print('valores_afec_static_1_Error', valores_afec_static_0_Error)
    return tensor_act,valores_afectados,mask_0,v_b,v_m,valores_afec_static_0_Error,valores_afec_static_1_Error

In [14]:
def TensorUpdateCiclo(error,v_b,c,valores_afec_static_0_Error,valores_afec_static_1_Error,mask,tensor_act,valores_afectados,mask_0):       
    values_to_change=tf.gather_nd(v_b,c)
    val_afec_0_Error_to_change=tf.gather_nd(valores_afec_static_0_Error,c)
    print('val_afec_0_Error_to_change',val_afec_0_Error_to_change)
    val_afec_1_Error_to_change=tf.gather_nd(valores_afec_static_1_Error,c)
    print('val_afec_1_Error_to_change',val_afec_1_Error_to_change)
    print('values_to_change',values_to_change)
    if error==1:
        tensor_round=ErrorAuno(values_to_change,mask)
        print('tensor_round',tensor_round)
    if error==0:
        tensor_round=ErrorAcero(values_to_change,mask)
        print('tensor_round',tensor_round)
    index=c.numpy()
    print('indice a camniar tensor act',index)
    print('valores_afectados',valores_afectados)
    val=tf.gather_nd(tf.where(valores_afectados),index)## tomo los indices del tensor original qu ese cambiaran
    print('val',val)
    tensor_act = tf.tensor_scatter_nd_update(tensor_act, val, tensor_round )
    valores_afectados=tf.tensor_scatter_nd_update(valores_afectados,val,tf.convert_to_tensor([False]*np.size(val)))
    mask_0=tf.add(mask_0,tf.size(val))
    print('mask_0 desdes update', mask_0)
    print('tensor tensor_act',tensor_act)
    print('valores_afectados update',valores_afectados) 
    #del tensor_round
    print('tensor_round',tensor_round)
    return tensor_act,valores_afectados,mask_0
    

In [12]:
## casos para el signo tanto para 0 en la primera posición como q

In [15]:
a=tf.math.not_equal(vb_and_mask,vm_and_mask)
print(a)
print('estoy calculando a y definiendo xq esta dado el error')
print('a vb_and_mask!=vm_and_mask',a)
error_a_1=tf.math.greater(v_m,v_b ) # El error es a 1 y aplico la variante con_error_a_1
print('b Vm>Vb',error_a_1)
index_values_error_a_1=tf.where(tf.logical_and(a,error_a_1)==True)
print('index_values_error_a_1',index_values_error_a_1)
print('tamaño de c',tf.size(index_values_error_a_1))
print(' Indices de los valores a transformar a 0',index_values_error_a_1)
values_to_change=tf.gather_nd(v_b,index_values_error_a_1)
print('mask_0 desdes update', mask_0)
#index=index_values_error_a_1.numpy() Esto da error por tanto uso la variante de abajo
index = tf.experimental.numpy.array(index_values_error_a_1)#para obtener el numero como índices
print('cnumpy',index)
print('valores_afectados',valores_afectados)
val=tf.gather_nd(tf.where(valores_afectados),index)## tomo los indices del tensor original qu ese cambiaran
print('val tipo',(val))
#val=ConvertoNumpy(val)
print('val tipo',type(val))

#
##### agraegado para si se encuentra error a 0 en la posición más significativa  esto 
error_a_0=tf.math.greater(v_b,v_m)
index_values_error_a_0=tf.where(tf.logical_and(a,error_a_0)==True)
print('index_values_error_a_0',index_values_error_a_0)
index_0=index_values_error_a_0.numpy()
print('cnumpy',index_0)
print('valores_afectados',valores_afectados)
val_0=tf.gather_nd(tf.where(valores_afectados),index_0)## tomo los indices del tensor original que se cambiaran

#print('val_0',val_0)
## Esta es la condición que da error en l proceso de inferencia cuando corro algún experimento real
# Aquí lo que hago es actualizar el tensor donde se encontraron valores con errores en el signo lo que se hace es 
#llamar a una función que los coloca en 0 y actualiza los valores que deben entrar alciclo
#val_0:índices del tensor original donde el cambio fue de un 1 por un 0 en el signo
#val:índices del tensor original donde el cambio fue de un 0 por un 1  en el signo

## entra a estos  if cuando hay error a 1 0 a cero en la posición más significativa  
#def f1():
#    print('f1')
#    TensorUpdatePosicionInicial(tensor_act, val_0, valores_afectados, mask_0, tensor_with_error, faults)
##   
#    
#def f2():
#    print('f2')
##    return TensorUpdatePosicionInicial(tensor_act,val,valores_afectados,mask_0)
#tf.cond((tf.size(val))>0,f1(), f2())
if tf.size(val)> 0: 
    tensor_act,valores_afectados,mask_0,v_b,v_m,valores_afec_static_0_Error,valores_afec_static_1_Error=TensorUpdatePosicionInicial(tensor_act,val,valores_afectados,mask_0,tensor_with_error,faults)
#
if tf.size(val_0)>0:
    tensor_act,valores_afectados,mask_0,v_b,v_m,valores_afec_static_0_Error,valores_afec_static_1_Error=TensorUpdatePosicionInicial(tensor_act,val_0,valores_afectados,mask_0,tensor_with_error,faults)
#        
#    
#print('tensor_act',tensor_act)
##print('valores_afectados',valores_afectados)
#print('tensor_with_error',tensor_with_error)
#print('v_b',v_b)
#print('v_m',v_m)
#print('valores_afec_static_0_Error', valores_afec_static_0_Error)
#print('valores_afec_static_1_Error',valores_afec_static_1_Error)
mask=tf.bitwise.right_shift(mask,1)

tf.Tensor([False False False], shape=(3,), dtype=bool)
estoy calculando a y definiendo xq esta dado el error
a vb_and_mask!=vm_and_mask tf.Tensor([False False False], shape=(3,), dtype=bool)
b Vm>Vb tf.Tensor([ True  True  True], shape=(3,), dtype=bool)
index_values_error_a_1 tf.Tensor([], shape=(0, 1), dtype=int64)
tamaño de c tf.Tensor(0, shape=(), dtype=int32)
 Indices de los valores a transformar a 0 tf.Tensor([], shape=(0, 1), dtype=int64)
mask_0 desdes update tf.Tensor(0, shape=(), dtype=int32)
cnumpy tf.Tensor([], shape=(0, 1), dtype=int64)
valores_afectados tf.Tensor([ True  True  True], shape=(3,), dtype=bool)
val tipo tf.Tensor([], shape=(0, 1), dtype=int64)
val tipo <class 'tensorflow.python.framework.ops.EagerTensor'>
index_values_error_a_0 tf.Tensor([], shape=(0, 1), dtype=int64)
cnumpy []
valores_afectados tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [6]:
a=tf.math.not_equal(tf.bitwise.bitwise_and(v_b,32768),tf.bitwise.bitwise_and(v_m,32768))
print (a)

tf.Tensor([ True  True False False False  True], shape=(6,), dtype=bool)


In [7]:
val=tf.gather_nd(tf.where(valores_afectados),tf.where(a==True))
val

<tf.Tensor: shape=(3, 1), dtype=int64, numpy=
array([[0],
       [1],
       [5]], dtype=int64)>

In [58]:
 tensor=tf.tensor_scatter_nd_update(tensor_original, val, tf.zeros(val.shape))

InvalidArgumentError: cannot compute TensorScatterUpdate as input #2(zero-based) was expected to be a int32 tensor but is a float tensor [Op:TensorScatterUpdate]

In [ ]:
new_values = tf.where(tf.math.not_equal(tf.bitwise.bitwise_and(VB,0b11111111_11111111),tf.bitwise.bitwise_and(VM,0b11111111_11111111)),tf.zeros[])))

In [33]:
valores_afectados = tf.tensor_scatter_nd_update(valores_afectados, val, a)
valores_afectados

InvalidArgumentError: indices[0] = [5] does not index into shape [1] [Op:TensorScatterUpdate]

In [32]:
a=valores_afectados=(tf.math.logical_not(tf.gather_nd(valores_afectados, val)))
print(a)
                                              


tf.Tensor([False], shape=(1,), dtype=bool)


In [27]:
tf.gather_nd(tensor, tf.where(valores_afectados == True))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([56319,    22,     0])>

In [22]:
valores_afectados = tf.tensor_scatter_nd_update(valores_afectados, val_0, tf.convert_to_tensor([False]* tf.experimental.numpy.size(val_0) ))
valores_afectados

<tf.Tensor: shape=(8,), dtype=bool, numpy=array([False, False,  True,  True,  True, False, False, False])>

In [35]:
int('1101111111111111',2)

57343

## modificarlo porque en el caso donde hay 0 en la posición 1 no lo estaba contemplando

In [ ]:
values_to_run_with_error
valores_afec_static_0_Error_to_run
valores_afec_static_0_Error_to_run
values_to_change

In [16]:
from tipoError import ErrorAuno,ErrorAcero
def while_body(i,out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error):
    print('dentro del body')
    print('i',i)
    print('out que llega al body', out)
    print('tensor_act',tensor_act)
    print('tensor_original',tensor_original)
    print('mask',mask)
    print('mask_0',mask_0)
    print('v_m',v_m)
    print('v_b',v_b)
    print('tensor_with_error',tensor_with_error)
    #hay_cambios=tf.math.not_equal(tensor_original,tensor_act)
    #print('hay_cambios',hay_cambios)
    #stop_condition=tf.experimental.numpy.any(valores_afectados)
    #if stop_condition==False:
        
    ## Este if lo cree por si hay cambios antes de llegar al ciclo por haber errores e la posición 15 pero quizás ya o sea
    # necesraio analizar luego de experimentar  si mask_0 llega con valores a 1 es porque se hicieron cambios y se deben
    #analizar los btw con los valores resttantes sino todo se mantiene con los valores originales de entrada.
    if tf.reduce_sum(mask_0)>0:
        print('entre en condicion mask_0>0')
        print('valores donde debo correr el mask')
        
        vb_and_mask=tf.bitwise.bitwise_and(v_b,mask)
        print('vb_and_mask',vb_and_mask)
        vm_and_mask=tf.bitwise.bitwise_and(v_m,mask)
        print('vm_and_mask',vm_and_mask)  
    else:
        
         ### esta estructura cambiaria porque ya tendre solo los valores con problemas, tomaria valores de tensores variables 
         #inicializados en 0 hasta que tome sus valores luego del recorrido por el body
         ## el tensor control tomara un papel aca porque luego actualizaria el tensor_actu en los posiciones donde 
             #tensorcontrol sea false mas otra condicion mas o debo ir comparando el tensor actu con el original y envio los dos
        #valores_afectados=tf.math.not_equal(tensor_original,tensor_with_error)## inicialmente no hara nada xq son iguales
        print('entre en el else')
        vb_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_original,tf.where(valores_afectados==True)),mask)
        print('vb_and_mask',vb_and_mask)
        vm_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True)),mask)
        print('vm_and_mask',vm_and_mask) 
        print('v_b',v_b)
        print('v_m',v_m)
        
    a=tf.math.not_equal(vb_and_mask,vm_and_mask)
    print('estoy calculando a y definiendo xq esta dado el error')
    print('a vb_and_mask!=vm_and_mask',a)
    values_to_run=tf.gather_nd(v_b,tf.where(a==False))
    values_to_run_with_error=tf.gather_nd(v_m,tf.where(a==False))
    valores_afec_static_0_Error_to_run=tf.gather_nd(valores_afec_static_0_Error,tf.where(a==False))
    print('valores_afec_static_0_Error_to_run',valores_afec_static_0_Error_to_run)
    valores_afec_static_1_Error_to_run=tf.gather_nd(valores_afec_static_1_Error,tf.where(a==False))
    print('valores_afec_static_1_Error_to_run',valores_afec_static_1_Error_to_run)
    print('values_to_run', values_to_run)
    print(' values_to_run_with_error', values_to_run_with_error)
    #valores_afectados_to_run= valores_afectados
    #u=tf.size(values_to_run)>0
    
    
    b=tf.math.greater(v_m,v_b ) # El error es a 1 y aplico la variante con_error_a_1
    print('b Vm>Vb',b)
    c=tf.where(tf.logical_and(a,b)==True)
    #c=tf.where(tf.equal(a,b))
    print('tamaño de c',tf.size(c))
    print(' c Indices de los valores a transformar con la variante error a 1',c)
    
    error_a_0=tf.math.greater(v_b,v_m)
    print('error_a_0',error_a_0)
    index_values_error_a_0=tf.where(tf.logical_and(a,error_a_0)==True)
    #index_values_error_a_0=tf.where(error_a_0==True)
    print('index_values_error_a_0',index_values_error_a_0)
    print('vb',v_b)
    
        
   
    if tf.size(c)>0:
        error=1
        tensor_act,valores_afectados,mask_0= TensorUpdateCiclo(error,v_b,c,valores_afec_static_0_Error,valores_afec_static_1_Error,mask,tensor_act,valores_afectados,mask_0)
        #values_to_change=tf.gather_nd(v_b,c)
        #val_afec_0_Error_to_change=tf.gather_nd(valores_afec_static_0_Error,c)
        #print('val_afec_0_Error_to_change',val_afec_0_Error_to_change)
        #val_afec_1_Error_to_change=tf.gather_nd(valores_afec_static_1_Error,c)
        #print('val_afec_1_Error_to_change',val_afec_1_Error_to_change)
        #print('values_to_change',values_to_change)
        #tensor_round=ErrorAuno(values_to_change,mask,val_afec_0_Error_to_change,val_afec_1_Error_to_change)
        #print('tensor_round',tensor_round)
        #index=c.numpy()
        #print('indice a camniar tensor act',index)
        #print('valores_afectados',valores_afectados)
        #val=tf.gather_nd(tf.where(valores_afectados),index)## tomo los indices del tensor original qu ese cambiaran
        #print('val',val)
        #tensor_act = tf.tensor_scatter_nd_update(tensor_act, val, tensor_round )
        #valores_afectados=tf.tensor_scatter_nd_update(valores_afectados,val,tf.convert_to_tensor([False]*np.size(val)))
        #mask_0=tf.add(mask_0,tf.size(val))
        print('mask_0 desdes update', mask_0)
        print('tensor tensor_act',tensor_act)
        print('valores_afectados update',valores_afectados)                                              
    
    
        
        
        
    
        
    ##no es el que esta en mask en esse momento, retorno new mask, new_mask_0, tensor_act
    if tf.size(index_values_error_a_0)>0: 
        error=0
        print('dentro detf.size(error_a_0)>0 ')
        tensor_act,valores_afectados,mask_0= TensorUpdateCiclo(error,v_b,index_values_error_a_0,valores_afec_static_0_Error,valores_afec_static_1_Error,mask,tensor_act,valores_afectados,mask_0)
        #out=tf.constant(tf.math.subtract(out,tf.size(error_a_0)))
        #print('out',out)
        #mask_0=tf.tensor_scatter_nd_update(mask_0,error_a_0,tf.convert_to_tensor([1]*np.size(error_a_0)))
        print()
        #out=tf.constant(tf.math.subtract(out,tf.reduce_sum(mask_0)))
        #values_to_change=tf.gather_nd(v_b,index_values_error_a_0)
        #val_afec_0_Error_to_change=tf.gather_nd(valores_afec_static_0_Error,index_values_error_a_0)
        #print('val_afec_0_Error_to_change',val_afec_0_Error_to_change)
        #val_afec_1_Error_to_change=tf.gather_nd(valores_afec_static_1_Error,index_values_error_a_0)
        #print('val_afec_1_Error_to_change',val_afec_1_Error_to_change)
        #print('values_to_change',values_to_change)
        #tensor_round=ErrorAcero(values_to_change,mask,val_afec_0_Error_to_change,val_afec_1_Error_to_change)
        #index_0=index_values_error_a_0.numpy()
        #print('index_0',index_0)
        #print('valores_afectados',valores_afectados)
        #val_0=tf.gather_nd(tf.where(valores_afectados),index_0)## tomo los indices del tensor original qu ese cambiaran
        #print('val_0',val_0)
        #
        #tensor_act = tf.tensor_scatter_nd_update(tensor_act, val_0, tensor_round )
        #valores_afectados=tf.tensor_scatter_nd_update(valores_afectados,val_0,tf.convert_to_tensor([False]*np.size(val_0)))
        ##print('tensor_round en el body',tensor_round)
        print('tensor tensor_act',tensor_act)
        print('valores_afectados update',valores_afectados)        
        #mask_0=tf.add(mask_0,tf.size(val_0))
        print('mask_0 desdes update', mask_0)
    
        
        
        
    if tf.size(values_to_run)>0:
        #mask=mask>>1
        mask=tf.bitwise.right_shift(mask,1)
        print('dentro del if values to run',values_to_run)
        print('mask',mask)
        v_b=values_to_run
        v_m=values_to_run_with_error 
        valores_afec_static_0_Error=valores_afec_static_0_Error_to_run
        valores_afec_static_1_Error=valores_afec_static_1_Error_to_run
        print('v_b',v_b)
        print('v_m',v_m)
        print('valores_afec_static_0_Error',valores_afec_static_0_Error)
        print('valores_afec_static_1_Error',valores_afec_static_1_Error)
        
    
    
    if tf.experimental.numpy.any(valores_afectados)==False:
        print('dentro de condicion de parada')
        #tensor=tf.bitwise.bitwise_and(tensor_act,val_afec_0_Error_to_change)
        #print('n_v_b_1', tensor)
        #tensor_round=tf.bitwise.bitwise_or(tensor,val_afec_1_Error_to_change)
        print('valores_afectados',valores_afectados)
        print('tensor_act',tensor_act)
        i=16
        
    print('i',i) 
    
    
    return (i+1),out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error ## retorno los valores que aun no se han modificado por ninguna d elas variantes puesto que el bit con error     
    
i,out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error= tf.while_loop(
    lambda i, *_ : tf.less(i,out),  # condición -> revisar cada bit
     while_body,  # aqui todo lo que tengas que hacer de comparar los vectores (que estos los puedes definir por fuera
                 # o pasarlos a la misma función de while_body y no modificarlos)
    (i,out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error)  # valores iniciales
)   



dentro del body
i tf.Tensor(0, shape=(), dtype=int32)
out que llega al body tf.Tensor(16, shape=(), dtype=int32)
tensor_act tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)
tensor_original tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)
mask tf.Tensor(16384, shape=(), dtype=int32)
mask_0 tf.Tensor(0, shape=(), dtype=int32)
v_m tf.Tensor([16422   102 33283], shape=(3,), dtype=int32)
v_b tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)
tensor_with_error tf.Tensor([16422   102 33283], shape=(3,), dtype=int32)
entre en el else
vb_and_mask tf.Tensor([0 0 0], shape=(3,), dtype=int32)
vm_and_mask tf.Tensor([16384     0     0], shape=(3,), dtype=int32)
v_b tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)
v_m tf.Tensor([16422   102 33283], shape=(3,), dtype=int32)
estoy calculando a y definiendo xq esta dado el error
a vb_and_mask!=vm_and_mask tf.Tensor([ True False False], shape=(3,), dtype=bool)
valores_afec_static_0_Error_to_run tf.Tensor([49087 65471], shape=(2,

In [48]:
static_Error0_1= ([49087,16384],[49087,64],[65471,514]) 
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor_act ,faults[:,0])
print('tensor_original',tensor_original)
tensor_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print('tensor_final', tensor_with_error)

tensor_original tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)
tensor_final tf.Tensor([16384    64 33282], shape=(3,), dtype=int32)


In [73]:
static_Error0_1= ([7927,528],[28671,0],[57343,1024],[65535,12],[65518,4],[65535,32768],[49087,0] ,[49087,0])
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor_act ,faults[:,0])
print('faults[:,0]',faults[:,0])
tensor_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print(tensor_with_error)

faults[:,0] tf.Tensor([ 7927 28671 57343 65535 65518 65535 49087 49087], shape=(8,), dtype=int32)
tf.Tensor([  528     0 57343    28    14 32768    30    38], shape=(8,), dtype=int32)


In [ ]:
16384    64 33282

In [ ]:
## probar pasando un diccionario

In [ ]:
1000000000100101
0000000000100101

In [ ]:
inyectando errores tensor_act tf.Tensor([    0     0 57343    28    14     0    30    38],
                                        
 sin inyectar errores                     0     0 65535    16    31     0    30    38                                       

In [ ]:
32768 32768 65535    16    31     0    30    38

In [24]:
tensor=tf.convert_to_tensor( [ 0,0, 57344,    16,    16,  0,  30  , 38] ) 
static_0_Error=tf.convert_to_tensor([7927,28671,57343,65535,65518,65535,49087 ,49087])
static_1_Error=tf.convert_to_tensor([528,0,1024,12,4,32768,0,0 ])
tensor=tf.bitwise.bitwise_and(tensor,static_0_Error)
tensor=tf.bitwise.bitwise_or(tensor,static_1_Error)
tensor

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([  528,     0, 50176,    28,     4, 32768,    30,    38])>

In [ ]:
while:528,     0, 57343,    28,    14, 32768,    30,    38]
for   528,     0, 50176,    28,     4, 32768,    30,    38
org   40167 61311 64511    22      17    37    30    38
    


## Ciclo este corre ok sin tener en cuenta lo de los errores en 0 en la primera posición

In [33]:
def while_body(i,out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error):
    print('dentro del body')
    print('i',i)
    print('out que llega al body', out)
    print('tensor_act',tensor_act)
    print('tensor_original',tensor_original)
    print('mask',mask)
    print('mask_0',mask_0)
    #hay_cambios=tf.math.not_equal(tensor_original,tensor_act)
    #print('hay_cambios',hay_cambios)
    #stop_condition=tf.experimental.numpy.any(valores_afectados)
    #if stop_condition==False:
        
    ## Este if lo cree por si hay cambios antes de llegar al ciclo por haber errores e la posición 15 pero quizás ya o sea
    # necesraio analizar luego de experimentar  si mask_0 llega con valores a 1 es porque se hicieron cambios y se deben
    #analizar los btw con los valores resttantes sino todo se mantiene con los valores originales de entrada.
    if tf.reduce_sum(mask_0)>0:
        print('entre en condicion mask_0>0')
        print('valores donde debo correr el mask')
        
        vb_and_mask=tf.bitwise.bitwise_and(v_b,mask)
        print('vb_and_mask',vb_and_mask)
        vm_and_mask=tf.bitwise.bitwise_and(v_m,mask)
        print('vm_and_mask',vm_and_mask)  
    else:
        
         ### esta estructura cambiaria porque ya tendre solo los valores con problemas, tomaria valores de tensores variables 
         #inicializados en 0 hasta que tome sus valores luego del recorrido por el body
         ## el tensor control tomara un papel aca porque luego actualizaria el tensor_actu en los posiciones donde 
             #tensorcontrol sea false mas otra condicion mas o debo ir comparando el tensor actu con el original y envio los dos
        valores_afectados=tf.math.not_equal(tensor_original,tensor_with_error)## inicialmente no hara nada xq son iguales
        print('entre en el else')
        vb_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_original,tf.where(valores_afectados==True)),mask)
        print('vb_and_mask',vb_and_mask)
        vm_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True)),mask)
        print('vm_and_mask',vm_and_mask) 
        print('v_b',v_b)
        print('v_m',v_m)
        
    a=tf.math.not_equal(vb_and_mask,vm_and_mask)
    print('estoy calculando a y definiendo xq esta dado el error')
    print('a vb_and_mask!=vm_and_mask',a)
    values_to_run=tf.gather_nd(v_b,tf.where(a==False))
    values_to_run_with_error=tf.gather_nd(v_m,tf.where(a==False))
    valores_afec_static_0_Error_to_run=tf.gather_nd(valores_afec_static_0_Error,tf.where(a==False))
    print('valores_afec_static_0_Error_to_run',valores_afec_static_0_Error_to_run)
    valores_afec_static_1_Error_to_run=tf.gather_nd(valores_afec_static_1_Error,tf.where(a==False))
    print('valores_afec_static_1_Error_to_run',valores_afec_static_1_Error_to_run)
    
    print(' values_to_run_with_error', values_to_run_with_error)
    #valores_afectados_to_run= valores_afectados
    u=tf.size(values_to_run)>0
    
    
    b=tf.math.greater(v_m,v_b ) # El error es a 1 y aplico la variante con_error_a_1
    print('b Vm>Vb',b)
    c=tf.where(tf.equal(a,b))
    print('tamaño de c',tf.size(c))
    print(' c Indices de los valores a transformar con la variante error a 1',c)
    
    error_a_0=tf.math.greater(v_b,v_m)
    print('error_a_0',error_a_0)
    index_values_error_a_0=tf.where(error_a_0==True)
    print('index_values_error_a_0',index_values_error_a_0)
    
        
   
    if tf.size(c)>0:
        #out=tf.constant(tf.math.subtract(out,tf.size(c)))
        #print('out',out)
        #mask_0=tf.tensor_scatter_nd_update(mask_0,c,tf.convert_to_tensor([1]*np.size(c)))
        
        #out=tf.constant(tf.math.subtract(out,tf.reduce_sum(mask_0)))
        values_to_change=tf.gather_nd(v_b,c)
        val_afec_0_Error_to_change=tf.gather_nd(valores_afec_static_0_Error,c)
        print('val_afec_0_Error_to_change',val_afec_0_Error_to_change)
        val_afec_1_Error_to_change=tf.gather_nd(valores_afec_static_1_Error,c)
        print('val_afec_1_Error_to_change',val_afec_1_Error_to_change)
        print('values_to_change',values_to_change)
        tensor_round=ErrorAuno(values_to_change,mask,val_afec_0_Error_to_change,val_afec_1_Error_to_change)
        print('tensor_round',tensor_round)
        index=c.numpy()
        print('cnumpy',index)
        print('valores_afectados',valores_afectados)
        val=tf.gather_nd(tf.where(valores_afectados),index)## tomo los indices del tensor original qu ese cambiaran
        print('val',val)
        tensor_act = tf.tensor_scatter_nd_update(tensor_act, val, tensor_round )
        valores_afectados=tf.tensor_scatter_nd_update(valores_afectados,val,tf.convert_to_tensor([False]*np.size(val)))
        mask_0=tf.add(mask_0,tf.size(values_to_change))
        print('mask_0 desdes update', mask_0)
        
        #print('tensor_round en el body',tensor_round)
        print('tensor tensor_act',tensor_act)
        print('valores_afectados update',valores_afectados)                                              
    
    
        #mask=tf.bitwise.right_shift(mask,1)
        #print('mask despues del shift',mask)
    
        print('tf.less dentro del body',a)
        #tensor_act = ...## llamo a una funciíon a la que le paso los indices en el tensor original que cambie y los nuevos valores 
        #y hago el update
        #new_mask = mask>>1
        #print(new_mask)
        #mask = new_mask_binary 
        #i = sum_new_mask_binary
        print('out',out)
        print('i',i)
        
    
        
    ##no es el que esta en mask en esse momento, retorno new mask, new_mask_0, tensor_act
    if tf.size(index_values_error_a_0)>0: 
        print('dentro detf.size(error_a_0)>0 ')
        #out=tf.constant(tf.math.subtract(out,tf.size(error_a_0)))
        #print('out',out)
        #mask_0=tf.tensor_scatter_nd_update(mask_0,error_a_0,tf.convert_to_tensor([1]*np.size(error_a_0)))
        
        #out=tf.constant(tf.math.subtract(out,tf.reduce_sum(mask_0)))
        values_to_change=tf.gather_nd(v_b,error_a_0)
        val_afec_0_Error_to_change=tf.gather_nd(valores_afec_static_0_Error,error_a_0)
        print('val_afec_0_Error_to_change',val_afec_0_Error_to_change)
        val_afec_1_Error_to_change=tf.gather_nd(valores_afec_static_1_Error,error_a_0)
        print('val_afec_1_Error_to_change',val_afec_1_Error_to_change)
        print('values_to_change',values_to_change)
        tensor_round=ErrorAcero(values_to_change,mask,val_afec_0_Error_to_change,val_afec_1_Error_to_change)
        index=error_a_0.numpy()
        print('cnumpy',index)
        print('valores_afectados',valores_afectados)
        val=tf.gather_nd(tf.where(valores_afectados),index)## tomo los indices del tensor original qu ese cambiaran
        print('val',val)
        
        tensor_act = tf.tensor_scatter_nd_update(tensor_act, val, tensor_round )
        valores_afectados=tf.tensor_scatter_nd_update(valores_afectados,val,tf.convert_to_tensor([False]*np.size(val)))
        #print('tensor_round en el body',tensor_round)
        print('tensor tensor_act',tensor_act)
        print('valores_afectados update',valores_afectados)        
        mask_0=tf.add(mask_0,tf.size(values_to_change))
        print('mask_0 desdes update', mask_0)
    
        #mask=tf.bitwise.right_shift(mask,1)
        #print('mask despues del shift',mask)
    
        
        #tensor_act = ...## llamo a una funciíon a la que le paso los indices en el tensor original que cambie y los nuevos valores 
        #y hago el update
        #new_mask = mask>>1
        #print(new_mask)
        #mask = new_mask_binary 
        #i = sum_new_mask_binary
        #print('out',out)
       # print('i',i)
    if tf.size(values_to_run)>0:
        #mask=mask>>1
        mask=tf.bitwise.right_shift(mask,1)
        print('dentro del if values to run',values_to_run)
        print('mask',mask)
        v_b=values_to_run
        v_m=values_to_run_with_error 
        valores_afec_static_0_Error=valores_afec_static_0_Error_to_run
        valores_afec_static_1_Error=valores_afec_static_1_Error_to_run
    #i=tf.add(i, 1) 
    #print(i)
    
    if tf.experimental.numpy.any(valores_afectados)==False:
        #factor=2**11
        #tensor_act= tf.cast(tensor_act/factor,dtype=tf.float32)
        print(tensor_act)
        i=16
        
    print(i) 
    
    
    return (i+1),out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error ## retorno los valores que aun no se han modificado por ninguna d elas variantes puesto que el bit con error     
    
i,out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error= tf.while_loop(
    lambda i, *_ : tf.less(i,out),  # condición -> revisar cada bit
     while_body,  # aqui todo lo que tengas que hacer de comparar los vectores (que estos los puedes definir por fuera
                 # o pasarlos a la misma función de while_body y no modificarlos)
    (i,out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error)  # valores iniciales
)   

#Analizar porque donde vm_and mask es igual a mask es porque el error está en la primera posiscíon
#entonces actualizo el tensor con el valor de mask `10000000000000'
#y donde vale 0 hay que seguir corriendo el mask
#hacer esto en otra página y hacerlo con el tensor mas grande para avarcar mas variantes


In [35]:
bin(32767)

'0b111111111111111'

In [36]:
int('0010000000000000',2)

8192

In [ ]:
38     38  16384     64   -514 -16448 -16448 -16319  32769 -16448     -64 -16384 -16448 -16384 -16448 -16448 -16448    -64     69  32840
    128   1024  16384     80   4112     27  -2048  32986

In [ ]:
te_or= 38    38    38    38 32769 32769 32769 32769 32769 32769 32769 32769   32769 32769 32769 32769 32769 32769    69 32840    27    27    66    66      66    27 32986 32986

te_err= 49087 49087 49087 49087 65471 49151 65535 65535 65535 65535 49151 65471  65535 65471 65535 65535 65535 49151 49151 65407 32767 65019 65535 61439  65535 61439 65535 49151

In [ ]:
va_afec_0_Error =0     0   16384    64   514   16448  16448  49087     0  16448    64  16384  16448 16384 16448 16448 16448    64     0     0   128  1024 16384    16   4112     0  2048    64], 
val_afec_1_Error=49087 49087 49087   49087 65471  49151  65535 65535 65535  65535   49151 65471  65535 65471 65535 65535 65535 49151 49087 32639 32767 65017 65471 61439  65535 61423 65527 49151], 

In [ ]:
[ 4] [ 6] [ 7] [ 8] [ 9] [11] [12] [13] [14] [15] [16] [19] [20] [26]

In [84]:
bin(49152 )

'0b1100000000000000'

In [92]:
n_mask=16383
not_mask=np.invert(np.array([n_mask], dtype=np.uint16))
not_mask

array([49152], dtype=uint16)

In [ ]:
i=0   [ 0] [ 1] [ 2] [ 3] [18] [21] [22] [23] [24] [25]

In [ ]:
v_b=   0000000000100110  38
v_m=   1011111110111111  49087  cambio en la iteración 0 
mask=  1000000000000000
mask-1=0111111111111111 32767
n_mask=1000000000000000 32768
nvb=v_b and not_mask
0000000000100110 
1000000000000000
1000000000000000 and  32768
0000000000000000 error_0
0000000000000000 btw_and
1011111110111111 error_1 
1011111110111111 btw_or 49087
shift-49087=-16319


In [85]:
bin(16383 )

'0b11111111111111'

In [83]:
bin(49152)

'0b11111111111111'

In [86]:
int('1100000000000000',2)

49152

In [ ]:
i=1 [ 4] [ 6] [ 7] [ 8] [ 9] [11] [12] [13] [14] [15] [16] [19] [20] [26]


In [ ]:
tensor_original=  32769  32769 32769 32769 32769  32769   32769 32769 32769 32769 32769  32840    27  32986       

tensor_with err=  65471  65535 65535 65535 65535 65471    65535 65471 65535 65535 65535  65407 32767  65535 

In [ ]:
va_afec_0_Error =   514     16448  49087     0  16448     16384  16448 16384 16448 16448 16448         0   128    2048   , 
val_fec_1_Error=   65471    65535 65535   65535  65535    65471  65535 65471 65535 65535 65535      32639 32767    65527 ], 

In [ ]:
val_afec_0_Err[    514     16448  49087     0    16448    16384  16448  16384 16448 16448 16448     0   128  2048], shape=(14,)
val_afec_1_Error[  65471   65535   65535   65535 65535   65471  65535  65471 65535 65535 65535   32639 32767 65527], shape=(14,), dtype=int32)
values_to_change [32769 32769 32769 32769  32769 32769  32769 3 2769  32769 32769 32769 32840   27 32986], shape=(14,), dtype=int32)

In [44]:
bin(514 )

'0b1000000010'

In [ ]:
v_b=   1000000000000001 32769
v_m=   1111111110111111 65471 iteraciOn 
mask=  0100000000000000  16384
mask-1 0011111111111111  16383
n_mask=1100000000000000  49152
nvb=v_b and not_mask
1000000000000001
1100000000000000
1000000000000000 and 32768
0000001000000010 error_0 514
0000000000000000 btw_and
1111111110111111 error_1 65471
1111111110111111 65471




In [21]:
shift=2**15
shift


32768

In [23]:
shift-65471

-32703

In [ ]:
i=[ 5], [10], [17], [27]

In [ ]:
tensor_original:   32769  32769  32769    32986             
tensor_with_error:[ 49151  49151  49151  49151       

In [ ]:
val_afec_0_Error_to_change tf.Tensor([16448    64    64    64]
val_afec_1_Error_to_change tf.Tensor([49151 49151 49151 49151] 
values_to_change tf.Tensor([32769 32769 32769 32986] 

In [45]:
bin(16448)

'0b100000001000000'

In [43]:
int('1100000001000000',2)

49216

In [ ]:
v_b=   1000000000000001 32769
v_m=   1011111111111111 49151 
mask=  0010000000000000 8192
mask-1 0001111111111111 8191
n_mask=1110000000000000 57344
nvb=v_b and not_mask
1000000000000001
1110000000000000
1000000000000000 and 32768
1011111111111111 error_0 
1000000000000000 btw_and
0100000001000000 error_1 
1100000001000000 49216

In [ ]:
static_1_Error:[  0     0 16384    64   514 16448 16448 49087     0 16448    64 16384  16448 16384 16448 16448 16448    64     0     0   128  1024 16384    16
  4112     0  2048    64]
static_0_Error:[49087 49087 49087 49087 65471 49151 65535 65535 65535 65535 49151 65471  65535 65471 65535 65535 65535 49151 49087 32639 32767 65017 65471 61439
 65535 61423 65527 49151]

In [ ]:
tensor_original:[  38    38    38    38   32769  32769  32769  32769  32769  32769   32769  32769  32769 32769  32769  32769 32769  32769   69  32840    27    27     66      66      66      27     32986        32986]


tensowith_error:[  38    38  16422  102  33283  49217  49217  49087  32769  49217   32833  49153  49217  49153  49217  49217 49217  32833   69  32840   155    1051   16450    82     4178    27      35034      32986]

In [ ]:
                 38    38   16384   64  -514  -16448  -16448 -16319  32769 -16448   -64  -16384 -16448 -16384  -16448 -16448 -16448 -64    69 32840    128   1024    16384   80     4112    27  -2048 32986

In [12]:
bin(102)

'0b1100110'

In [ ]:
0100110
1100110