In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.python.keras import backend as K
import tensorflow as tf
import collections
import numpy as np
from openpyxl import load_workbook
from openpyxl import Workbook
from pandas import ExcelWriter
from funciones import ErrorAuno,ErrorAcero

from tensorflow.keras.layers import (Activation, AveragePooling2D, BatchNormalization, Cropping2D,
                                     Concatenate, Conv1D, Conv2D, Dense, DepthwiseConv2D, Dropout,
                                     Embedding, Flatten, GlobalAveragePooling2D, Lambda, MaxPool2D,
                                     MaxPooling1D, ReLU, Reshape, ZeroPadding2D)

In [ ]:
#It is intended to make an approximation to the number to be written in buffer, taking into account that there are 
#positions with errors, respecting these physical errors, an approximation is made to the ideal number that should be
#written.
# We have certain values to write and simulate the injection of the errors given by changes of 1 by 0 or vice versa 

In [ ]:
test
VB:38 38 32769
Vm: 16422   102 33283 
error _0 49087 ,49087,49087
error_1 16384, 64,514


0000000000100110 38 vb
0100000000100110 16422 vm
0100000000000000 mask 16384 error 1 vm>vb
0011111111111111 mask-1 16383
1100000000000000 n_mask 49152
0000000000100110 vb
0000000000000000 btwand
1011111110111111 and error_0 49087
0000000000000000
0100000000000000 or 16384
010000000000000016384

numero 2
0000000000100110 38
0000000001100110 102
00000000010000000 mask 128
00000000001111111mas-1 127
11111111110000000 n_mask
0000000000100110
0000000000000000 and n_mask
1011111110111111
0000000000000000
0000000001000000
0000000001000000 64
numeo 3
1000000000000001 32769
1000001000000011 33283
0000001000000000 512
0000000111111111 masl-1 511
1111111000000000n_mask
1000000000000001
1000000000000000 32768
1011111110111111
1000000000000000b32768
0000001000000010
1000001000000010 33282








    

In [ ]:
#Error injection

## Test 1

In [2]:
import tensorflow as tf
tensor_original=tf.convert_to_tensor([38, 38, 32769])
static_Error0_1= ([49087,16384],[49087,64],[65471,514]) 
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor_original,faults[:,0])
print('tensor_original',tensor_original)
tensor_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print('tensor_with_error',tensor_with_error)

tensor_original tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)
tensor_with_error tf.Tensor([16422   102 33283], shape=(3,), dtype=int32)


In [ ]:
##  Run affected_values

## Test 2

In [3]:
import tensorflow as tf
import numpy as np
tensor_original=tf.convert_to_tensor([40167,61311,64511,22,17,37,30,38 ])
print('tensor_original',tensor_original)
static_Error0_1= ([7927,528],[28671,0],[57343,1024],[65535,12],[65518,4],[65535,32768],[49087,0] ,[49087,0])
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor_original,faults[:,0])
print('faults[:,0]',faults[:,0])
tensor_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print(tensor_with_error)



tensor_original tf.Tensor([40167 61311 64511    22    17    37    30    38], shape=(8,), dtype=int32)
faults[:,0] tf.Tensor([ 7927 28671 57343 65535 65518 65535 49087 49087], shape=(8,), dtype=int32)
tf.Tensor([ 7927 28543 57343    30     4 32805    30    38], shape=(8,), dtype=int32)


In [ ]:
vb 40167,61311,64511
error_0: 7927,28671,57343
error_1: 528,0,1024
0.Antes de entrar al ciclo
1001110011100111 vb 40167
0001111011110111 vm 7927
0001111011110111 error_0 7927
0001111011110111 and
0000001000010000 error_1 528
0001111011110111 7927
Prueba
mask=32768     
n_mask=mask-1   0111111111111111
000000000000000

1. Antes de entrar al ciclo
1110111101111111 vb 61311
0110111101111111 vm 28543 
0110111111111111 error_0 28671
0110111101111111 28543
0000000000000000 error_1 
0110111101111111 28543
Prueba
mask=32768     
n_mask=(mask-1) 0111111111111111
1110111101111111 vb
0111111111111111 n_mask
1111111111111111 or 65535
0110111111111111 and error_0 28671
0110111111111111
0000000000000000 error_1
0110111111111111 or  28671 

3. iteración i=1
1111101111111111 vb 64511
1101111111111111 v_m 57343
1101111111111111 error_0 57343
1101101111111111
0000010000000000 error_1 1024
1101111111111111 57343

Prueba
mask=8192 0010000000000000    
n_mask=(mask-1)0001111111111111
1111101111111111 vb 64511
0001111111111111  n_mask
1111111111111111 or n_mask
1101111111111111 error_0 57343
1101111111111111 and
0000010000000000 error_1 1024
1101111111111111  57343


 528     0 50176

1111101111111111v_b
1000000000000000
1000000000000000 vb_mask
1101111111111111- v_m
1000000000000000
1000000000000000 vm_mask
vb_mask!=vm_mask  false
v_m>v_b false



## Declaration of variables and preparation of data entering the cycle

In [ ]:
#values_to_run
#mask: mask to keep track of when an error occurs(initially 10000000_0000000) 32768
#v_m:values affected by errors
#v_b:values that should be written
#mask_0:
#affected_values: True and False matrix of control changes (True and False) will initially be set 
#to True for positions where there are errors.
#valores_afec_static_0_Error
#valores_afec_static_1_Error
#vb_and_mask:tf.bitwise.bitwise_and(vb,mask)
#vm_and_mask:tf.bitwise.bitwise_and(vm,mask)
#tensor_act:tensor to be upgraded, initially I match it to the original one.
#values_to_run

In [4]:
#Se crea un tensor variable donde se guardarán los valores en cada ciclo que aún no se han encontrado la posición con error
#y hay que continuar analizando con mask>>1
# se cra un tensor con el valos de la máscara inicial la cual es 1000000000000000
values_to_run=tf.Variable(0)
mask=tf.convert_to_tensor(32768)

#crea un tensor de (T and F),donde en T están los valores afectados por los errores inyectados
# esta matriz es la que controla si ya no hay cambios pendientes porque todos los valores han sido analizados y
#detiene el ciclo para no iterar innecesariamente

valores_afectados=tf.math.not_equal(tensor_original,tensor_with_error)
print('valores_afectados',valores_afectados)  

# Se extraen los valores que fueron afectados por los errores
v_m=tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True))
print('valores afectados por los errores' ,v_m)

#valores que se deberian escribir
v_b=tf.gather_nd(tensor_original,tf.where(valores_afectados==True))
print('valores que se deberian escribir' ,v_b)
mask_0=tf.constant(0)
print('mask_0',mask_0)

# inicializo los valores de comienzo y fin del ciclo teniendo en cuenta que pueden haber errores hasta la posición 15 de
# una palabra
i=tf.constant(0)
out=tf.constant(16)
print(' out inicial',(out))
print('i inicial', i)


#matriz_control(esta la cree pero al final no la uso luego que verifique todo puede ser eliminada sino hace falta)
#matriz_control=tf.equal(tensor_original,tensor_with_error)
matriz_control_cambios=tf.equal(v_b,v_m)
print('matriz_control_cambios',matriz_control_cambios)

# Tensores con los valores de errores en 0 y 1 que propiciaron cambios en el tensor original
valores_afec_static_0_Error=tf.gather_nd(faults[:,0], tf.where(tf.math.not_equal(tensor_original,tensor_with_error)))
valores_afec_static_1_Error=tf.gather_nd(faults[:,1], tf.where(tf.math.not_equal(tensor_original,tensor_with_error)))
print('valores_afec_static_0_Error',valores_afec_static_0_Error)
print('valores_afec_static_1_Error',valores_afec_static_1_Error)

vb_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_original,tf.where(valores_afectados==True)),mask)
print('vb_and_mask',vb_and_mask)
vm_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True)),mask)
vm_and_mask

tensor_act=tensor_original 

valores_afectados tf.Tensor([ True  True  True  True  True  True False False], shape=(8,), dtype=bool)
valores afectados por los errores tf.Tensor([ 7927 28543 57343    30     4 32805], shape=(6,), dtype=int32)
valores que se deberian escribir tf.Tensor([40167 61311 64511    22    17    37], shape=(6,), dtype=int32)
mask_0 tf.Tensor(0, shape=(), dtype=int32)
 out inicial tf.Tensor(16, shape=(), dtype=int32)
i inicial tf.Tensor(0, shape=(), dtype=int32)
matriz_control_cambios tf.Tensor([False False False False False False], shape=(6,), dtype=bool)
valores_afec_static_0_Error tf.Tensor([ 7927 28671 57343 65535 65518 65535], shape=(6,), dtype=int32)
valores_afec_static_1_Error tf.Tensor([  528     0  1024    12     4 32768], shape=(6,), dtype=int32)
vb_and_mask tf.Tensor([32768 32768 32768     0     0     0], shape=(6,), dtype=int32)
vm_and_mask tf.Tensor([    0     0 32768     0     0 32768], shape=(6,), dtype=int32)


In [14]:

#a:Array of True and False where True is the positions where vb_and_mask and vm_and_mask are different
# therefore there is an error in the most significant position 
#b:True and False matrix where True is the position where (v_m>v_b ) is true. 
#c: Index where the matrix a and b are true therefore the error is given by a 1 
#values_to_change: the values of v_b at positions c to be sent to the ErroraUno function for transformation.
#val_afec_0_Error_to_change:Values corresponding to the error to 0 
#val_afec_1_Error_to_change:values that correspond to the error to 1 I think they are no longer needed. 
#index:returns the value of c in a numpy variable
#val:returns a list of elements corresponding to the indices of affected values ==True which will be the indices to be transformed
#error_a_0: Array of True and False where True is the position where (v_b>v_m ) is satisfied.
#index_values_error_a_0:Index where matrix a and error_a_0 which are true so the error is given by a 0 
#val_0=returns a list of elements corresponding to the indices of affected values ==True which will be the indices to transform.
#tensor_act: returns the tensor already transformed with the elements in the corresponding positions where the analyzed cases have been found.


In [ ]:
#This function takes the indexes in the original matrix where the errors are given in the most significant bit and sets 
#the value to 0. This is done before entering the cycle with the initial mask, then the control matrix is updated in the 
#positions where changes were made and set to false, the values pending analysis are extracted with mask-1.

In [5]:
def TensorUpdatePosicionInicial(tensor_act,val,valores_afectados,mask_0,tensor_with_error,faults): 
    print('Dentro de TensorUpdatePosicionInicial')
    tensor_act = tf.tensor_scatter_nd_update(tensor_act, val, tf.convert_to_tensor([0]*np.size(val) ))
    valores_afectados=tf.tensor_scatter_nd_update(valores_afectados,val,tf.convert_to_tensor([False]*np.size(val)))
    mask_0=tf.add(mask_0,tf.size(val)) 
    v_b=tf.gather_nd(tensor_act,tf.where(valores_afectados==True))
    print('v_b',v_b)
    v_m=tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True) )
    valores_afec_static_0_Error=tf.gather_nd(faults[:,0],tf.where(valores_afectados==True))
    valores_afec_static_1_Error=tf.gather_nd(faults[:,1],tf.where(valores_afectados==True))
    return tensor_act,valores_afectados,mask_0,v_b,v_m,valores_afec_static_0_Error,valores_afec_static_1_Error

In [ ]:
#This function performs the changes already within the cycle, taking into account the type of error,
#if it is the change of a 1 for a 0, an algorithm is performed, and if it is the other way around, another algorithm
#is performed, seeking to approximate values.

In [6]:
def TensorUpdateCiclo(error,v_b,c,valores_afec_static_0_Error,valores_afec_static_1_Error,mask,tensor_act,valores_afectados,mask_0):       
    values_to_change=tf.gather_nd(v_b,c)
    val_afec_0_Error_to_change=tf.gather_nd(valores_afec_static_0_Error,c)
    val_afec_1_Error_to_change=tf.gather_nd(valores_afec_static_1_Error,c)
    if error==1:
        tensor_round=ErrorAuno(values_to_change,mask)
        
    if error==0:
        tensor_round=ErrorAcero(values_to_change,mask)
        
    index=c.numpy()
    val=tf.gather_nd(tf.where(valores_afectados),index)## tomo los indices del tensor original qu ese cambiaran
    
    tensor_act = tf.tensor_scatter_nd_update(tensor_act, val, tensor_round )
    valores_afectados=tf.tensor_scatter_nd_update(valores_afectados,val,tf.convert_to_tensor([False]*np.size(val)))
    mask_0=tf.add(mask_0,tf.size(val))
    return tensor_act,valores_afectados,mask_0
    

In [7]:
a=tf.math.not_equal(vb_and_mask,vm_and_mask)
# error a 1
error_a_1=tf.math.greater(v_m,v_b ) 
index_values_error_a_1=tf.where(tf.logical_and(a,error_a_1)==True)
values_to_change=tf.gather_nd(v_b,index_values_error_a_1)
index = tf.experimental.numpy.array(index_values_error_a_1)#para obtener el numero como índices
val=tf.gather_nd(tf.where(valores_afectados),index)## tomo los indices del tensor original qu ese cambiaran
val = tf.cast(val, dtype=tf.int32)

#### error to 0 
error_a_0=tf.math.greater(v_b,v_m)
index_values_error_a_0=tf.where(tf.logical_and(a,error_a_0)==True)
index_0=index_values_error_a_0.numpy()
val_0=tf.gather_nd(tf.where(valores_afectados),index_0)## tomo los indices del tensor original que se cambiaran
val_0 = tf.cast(val_0, dtype=tf.int32)


if tf.size(val)> 0: 
    tensor_act,valores_afectados,mask_0,v_b,v_m,valores_afec_static_0_Error,valores_afec_static_1_Error=TensorUpdatePosicionInicial(tensor_act,val,valores_afectados,mask_0,tensor_with_error,faults)

if tf.size(val_0)>0:
    tensor_act,valores_afectados,mask_0,v_b,v_m,valores_afec_static_0_Error,valores_afec_static_1_Error=TensorUpdatePosicionInicial(tensor_act,val_0,valores_afectados,mask_0,tensor_with_error,faults)
        
    
print('tensor_act',tensor_act)

mask=tf.bitwise.right_shift(mask,1)

Dentro de TensorUpdatePosicionInicial
v_b tf.Tensor([40167 61311 64511    22    17], shape=(5,), dtype=int32)
Dentro de TensorUpdatePosicionInicial
v_b tf.Tensor([64511    22    17], shape=(3,), dtype=int32)
tensor_act tf.Tensor([    0     0 64511    22    17     0    30    38], shape=(8,), dtype=int32)


In [ ]:
values_to_run_with_error
valores_afec_static_0_Error_to_run
valores_afec_static_0_Error_to_run
values_to_change

In [8]:

def while_body(i,out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error):
    
    if tf.reduce_sum(mask_0)>0:
        vb_and_mask=tf.bitwise.bitwise_and(v_b,mask)
        vm_and_mask=tf.bitwise.bitwise_and(v_m,mask)
        
    else:
        
         
        vb_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_original,tf.where(valores_afectados==True)),mask)
        print('vb_and_mask',vb_and_mask)
        vm_and_mask=tf.bitwise.bitwise_and(tf.gather_nd(tensor_with_error,tf.where(valores_afectados==True)),mask)
        print('vm_and_mask',vm_and_mask) 
        print('v_b',v_b)
        print('v_m',v_m)
        
    a=tf.math.not_equal(vb_and_mask,vm_and_mask)
    print('calculating a and defining xq is given error')
    print('a vb_and_mask!=vm_and_mask',a)
    values_to_run=tf.gather_nd(v_b,tf.where(a==False))
    values_to_run_with_error=tf.gather_nd(v_m,tf.where(a==False))
    valores_afec_static_0_Error_to_run=tf.gather_nd(valores_afec_static_0_Error,tf.where(a==False))
    valores_afec_static_1_Error_to_run=tf.gather_nd(valores_afec_static_1_Error,tf.where(a==False))
    
    
    b=tf.math.greater(v_m,v_b ) # El error es a 1 y aplico la variante con_error_a_1
    print('b Vm>Vb',b)
    c=tf.where(tf.logical_and(a,b)==True)
    #c=tf.where(tf.equal(a,b))
    print('tamaño de c',tf.size(c))
    print(' Indexes of the values to be transformed with the error variant to 1',c)
    
    error_a_0=tf.math.greater(v_b,v_m)
    print('error_a_0',error_a_0)
    index_values_error_a_0=tf.where(tf.logical_and(a,error_a_0)==True)
    print('Indexes of the values to be transformed with the error variant to 1',index_values_error_a_0)
   
    
        
   
    if tf.size(c)>0:
        error=1
        tensor_act,valores_afectados,mask_0= TensorUpdateCiclo(error,v_b,c,valores_afec_static_0_Error,valores_afec_static_1_Error,mask,tensor_act,valores_afectados,mask_0)
        
        print('mask_0 desdes update', mask_0)
        print('tensor tensor_act',tensor_act)
        print('valores_afectados update',valores_afectados)                                              
       
    ##no es el que esta en mask en esse momento, retorno new mask, new_mask_0, tensor_act
    if tf.size(index_values_error_a_0)>0: 
        error=0
        print('dentro detf.size(error_a_0)>0 ')
        tensor_act,valores_afectados,mask_0= TensorUpdateCiclo(error,v_b,index_values_error_a_0,valores_afec_static_0_Error,valores_afec_static_1_Error,mask,tensor_act,valores_afectados,mask_0)
        print('tensor tensor_act',tensor_act)
        print('valores_afectados update',valores_afectados)        
        print('mask_0 desdes update', mask_0)
    
        
        
        
    if tf.size(values_to_run)>0:
        mask=tf.bitwise.right_shift(mask,1)
        v_b=values_to_run
        v_m=values_to_run_with_error 
        valores_afec_static_0_Error=valores_afec_static_0_Error_to_run
        valores_afec_static_1_Error=valores_afec_static_1_Error_to_run
        print('v_b',v_b)
        print('v_m',v_m)
        print('valores_afec_static_0_Error',valores_afec_static_0_Error)
        print('valores_afec_static_1_Error',valores_afec_static_1_Error)
        
    
    
    if tf.experimental.numpy.any(valores_afectados)==False:
        print('dentro de condicion de parada')
        print('valores_afectados',valores_afectados)
        print('tensor_act',tensor_act)
        i=16
        
    print('i',i) 
    
    
    return (i+1),out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error ## retorno los valores que aun no se han modificado por ninguna d elas variantes puesto que el bit con error     
    
i,out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error= tf.while_loop(
    lambda i, *_ : tf.less(i,out),  # condición -> revisar cada bit
     while_body,  # aqui todo lo que tengas que hacer de comparar los vectores (que estos los puedes definir por fuera
                 # o pasarlos a la misma función de while_body y no modificarlos)
    (i,out,mask,mask_0,tensor_original,tensor_act,v_m,v_b,tensor_with_error,values_to_run,valores_afectados,valores_afec_static_0_Error,valores_afec_static_1_Error)  # valores iniciales
)   


calculating a and defining xq is given error
a vb_and_mask!=vm_and_mask tf.Tensor([False False False], shape=(3,), dtype=bool)
b Vm>Vb tf.Tensor([False  True False], shape=(3,), dtype=bool)
tamaño de c tf.Tensor(0, shape=(), dtype=int32)
 Indexes of the values to be transformed with the error variant to 1 tf.Tensor([], shape=(0, 1), dtype=int64)
error_a_0 tf.Tensor([ True False  True], shape=(3,), dtype=bool)
Indexes of the values to be transformed with the error variant to 1 tf.Tensor([], shape=(0, 1), dtype=int64)
v_b tf.Tensor([64511    22    17], shape=(3,), dtype=int32)
v_m tf.Tensor([57343    30     4], shape=(3,), dtype=int32)
valores_afec_static_0_Error tf.Tensor([57343 65535 65518], shape=(3,), dtype=int32)
valores_afec_static_1_Error tf.Tensor([1024   12    4], shape=(3,), dtype=int32)
i tf.Tensor(0, shape=(), dtype=int32)
calculating a and defining xq is given error
a vb_and_mask!=vm_and_mask tf.Tensor([ True False False], shape=(3,), dtype=bool)
b Vm>Vb tf.Tensor([False  Tr

# Paso final inyectar los errores originales según ejemplo correspondiente

In [10]:
static_Error0_1= ([49087,16384],[49087,64],[65471,514]) 
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor_act ,faults[:,0])
print('tensor_original',tensor_original)
tensor_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print('tensor_final', tensor_with_error)

tensor_original tf.Tensor([   38    38 32769], shape=(3,), dtype=int32)
tensor_final tf.Tensor([16384    64 33282], shape=(3,), dtype=int32)


In [18]:
static_Error0_1= ([7927,528],[28671,0],[57343,1024],[65535,12],[65518,4],[65535,32768],[49087,0] ,[49087,0])
faults=tf.convert_to_tensor(static_Error0_1)
tensor  = tf.bitwise.bitwise_and(tensor_act ,faults[:,0])
print('faults[:,0]',faults[:,0])
tensor_with_error  = tf.bitwise.bitwise_or(tensor,faults[:,1])
print(tensor_with_error)

faults[:,0] tf.Tensor([ 7927 28671 57343 65535 65518 65535 49087 49087], shape=(8,), dtype=int32)
tf.Tensor([  528     0 57343    28    14 32768    30    38], shape=(8,), dtype=int32)
